---
- name: Deploy metallb to cluster
  hosts: controlplane[0]
  become: yes

  tasks:
    - name: Check if metallb is already deployed
      ansible.builtin.command: kubectl get pods -n metallb-system
      register: metallb_check
      changed_when: false
      failed_when: false

    - name: Create metallb namespace
      kubernetes.core.k8s:
        state: present
        resource_definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: metallb-system
            labels:
              pod-security.kubernetes.io/enforce: privileged
              pod-security.kubernetes.io/audit: privileged
              pod-security.kubernetes.io/warn: privileged
      when: "'No resources found' in metallb_check.stderr"

    - name: Add metallb helm repo
      kubernetes.core.helm_repository:
        name: metallb
        repo_url: https://metallb.github.io/metallb
        kubeconfig: /home/vagrant/.kube/config
      when: "'No resources found' in metallb_check.stderr"

    - name: Install metallb with Helm
      kubernetes.core.helm:
        name: metallb
        chart_ref: metallb/metallb
        namespace: metallb-system
        state: present
        kubeconfig: /home/vagrant/.kube/config
      when: "'No resources found' in metallb_check.stderr"