---
- name: Deploy cert-manager
  hosts: controlplane[0]
  become: true

  tasks:
    - name: Add Jetstack Helm repository
      kubernetes.core.helm_repository:
        name: cert-manager
        repo_url: https://charts.jetstack.io
        state: present

    - name: Install cert-manager Helm chart
      kubernetes.core.helm:
        name: cert-manager
        chart_ref: cert-manager/cert-manager
        namespace: cert-manager
        create_namespace: true
        values:
          crds:
            enabled: true
          enableCertificateOwnerRef: false
          # config:
          #   apiVersion: controller.config.cert-manager.io/v1alpha1
          #   kind: ControllerConfiguration
          #   enableGatewayAPI: true
          dns01RecursiveNameservers: "1.1.1.1:43,1.0.0.1:53"
          dns01RecursiveNameserversOnly: true
          prometheus:
            servicemonitor:
              enabled: true
              labels:
                release: prometheus
        state: present

    - name: Deploy InfisicalSecret for cert-manager secrets
      kubernetes.core.k8s:
        state: present
        definition: |
          {% raw %}
          apiVersion: secrets.infisical.com/v1alpha1
          kind: InfisicalSecret
          metadata:
            name: cert-manager-secrets
            namespace: cert-manager
          spec:
            authentication:
              universalAuth:
                secretsScope:
                  projectSlug: "homelab-b-h-sw"
                  envSlug: "prod"
                  secretsPath: "/"
                credentialsRef:
                  secretName: universal-auth-credentials
                  secretNamespace: infisical
            managedKubeSecretReferences:
              - secretName: cert-manager-secrets
                secretNamespace: cert-manager
                creationPolicy: "Owner"
                template:
                  data:
                    CLOUDFLARE_TOKEN: "{{ .CLOUDFLARE_TOKEN.Value }}"
          {% endraw %}

    - name: Generate cert-manager issuer manifest from template
      ansible.builtin.template:
        src: manifests/certissuer.yaml.j2
        dest: /tmp/certissuer.yaml
        mode: '0644'
      delegate_to: localhost
      become: false

    - name: Deploy cert-manager issuers
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', '/tmp/certissuer.yaml') }}"
