---
- name: Deploy Rook-Ceph
  hosts: controlplane[0]
  become: yes

  tasks:
    - name: Add Rook Ceph Helm Repo
      kubernetes.core.helm_repository:
        name: rook-release
        repo_url: https://charts.rook.io/release

    - name: Install Rook-Ceph Operator
      kubernetes.core.helm:
        name: rook-ceph
        chart_ref: rook-release/rook-ceph
        namespace: rook-ceph
        create_namespace: true
        values:
          image:
            repository: mirror.gcr.io/rook/ceph
            csi:
              serviceMonitor:
                enabled: true
                interval: 10s
                labels:
                  release: prometheus
            enableDiscoveryDaemon: true
            monitoring:
              enabled: true
        state: present

    - name: Install Rook Ceph Cluster
      kubernetes.core.helm:
        name: rook-ceph-cluster
        chart_ref: rook-release/rook-ceph-cluster
        namespace: rook-ceph
        values:
          operatorNamespace: rook-ceph
          toolbox:
            enabled: true
          cephClusterSpec:
            mgr:
              count: 2
              allowMultiplePerNode: false
              modules:
                - name: rook
                  enabled: true
            dashboard:
              enabled: true
              ssl: false
          cephObjectStores: null
          cephBlockPools: null
          cephFileSystems:
          - name: ceph-filesystem
            spec:
              metadataPool:
                replicated:
                  size: 3
              dataPools:
                - failureDomain: host
                  replicated:
                    size: 3
                  name: data0
              metadataServer:
                activeCount: 1
                activeStandby: true
                resources:
                  limits:
                    memory: "4Gi"
                  requests:
                    cpu: "1000m"
                    memory: "4Gi"
                priorityClassName: system-cluster-critical
            storageClass:
              enabled: true
              isDefault: true
              name: ceph-filesystem
              reclaimPolicy: Retain
              allowVolumeExpansion: true
              volumeBindingMode: "Immediate"
              annotations: {}
              labels: {}
              mountOptions: []
              # see https://github.com/rook/rook/blob/master/Documentation/Storage-Configuration/Shared-Filesystem-CephFS/filesystem-storage.md#provision-storage for available configuration
              parameters:
                # The secrets contain Ceph admin credentials.
                csi.storage.k8s.io/provisioner-secret-name: rook-csi-cephfs-provisioner
                csi.storage.k8s.io/provisioner-secret-namespace: "rook-ceph"
                csi.storage.k8s.io/controller-expand-secret-name: rook-csi-cephfs-provisioner
                csi.storage.k8s.io/controller-expand-secret-namespace: "rook-ceph"
                csi.storage.k8s.io/controller-publish-secret-name: rook-csi-cephfs-provisioner
                csi.storage.k8s.io/controller-publish-secret-namespace: "rook-ceph"
                csi.storage.k8s.io/node-stage-secret-name: rook-csi-cephfs-node
                csi.storage.k8s.io/node-stage-secret-namespace: "rook-ceph"
                # Specify the filesystem type of the volume. If not specified, csi-provisioner
                # will set default as `ext4`. Note that `xfs` is not recommended due to potential deadlock
                # in hyperconverged settings where the volume is mounted on the same node as the osds.
                csi.storage.k8s.io/fstype: ext4
          monitoring:
            enabled: true
        state: present