---
- name: Deploy ArgoCD and required secrets
  hosts: controlplane[0]
  become: true

  tasks:
    - name: Create Infisical namespace
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: infisical

    - name: Create Infisical secret with client credentials
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: universal-auth-credentials
            namespace: infisical
          type: Opaque
          data:
            clientId: "{{ lookup('env', 'INFISICAL_UNIVERSAL_AUTH_CLIENT_ID') | b64encode }}"
            clientSecret: "{{ lookup('env', 'INFISICAL_UNIVERSAL_AUTH_CLIENT_SECRET') | b64encode }}"

    - name: Create ArgoCD namespace
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: argocd

    - name: Create ArgoCD Git repo_url
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: github-repo
            namespace: argocd
            labels:
              argocd.argoproj.io/secret-type: repository
          type: Opaque
          stringData:
            sshPrivateKey: "{{ lookup('env', 'sshPrivateKey') }}"
            type: "git"
            url: "git@github.com:mscreations/cluster-apps.git"

    - name: Install ArgoCD
      kubernetes.core.k8s:
        definition: "{{ lookup('kubernetes.core.kustomize', dir='./cluster-apps/apps/infra/argocd', binary_path='/usr/bin/kubectl') }}"
        server_side_apply:
          field_manager: ansible
          force_conflicts: true

    - name: Wait for all ArgoCD deployments to be ready
      kubernetes.core.k8s_info:
        api_version: apps/v1
        kind: Deployment
        namespace: argocd
      register: argocd_deployments
      until: >
        argocd_deployments.resources | length > 0 and
        (
          argocd_deployments.resources
          | map(attribute='status.availableReplicas')
          | map('default', 0)
          | list
          ==
          argocd_deployments.resources
          | map(attribute='spec.replicas')
          | list
        )
      retries: 30
      delay: 10

    - name: Install Projects
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', '../cluster-apps/bootstrap/projects.yaml') | from_yaml_all }}"

    - name: Install Infra ApplicationSet
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', '../cluster-apps/bootstrap/infra-applicationset.yaml') | from_yaml_all }}"
