- name: Install ArgoCD
  hosts: controlplane[0]
  become: true

  tasks:
    - name: Add ArgoCD Helm Repo
      kubernetes.core.helm_repository:
        name: argo
        repo_url: https://argoproj.github.io/argo-helm

    - name: Copy values.yaml to remote
      ansible.builtin.copy:
        src: "{{ item.local }}"
        dest: "{{ item.remote }}"
        mode: '0644'
      with_items:
        - { local: '../cluster-apps/bootstrap/argocd/values.yaml', remote: '/tmp/argocd-values.yaml' }
        - { local: '../cluster-apps/bootstrap/repo-secret.yaml', remote: '/tmp/repo-secret.yaml' }
        - { local: '../cluster-apps/bootstrap/applicationset.yaml', remote: '/tmp/applicationset.yaml' }

    - name: Install ArgoCD
      kubernetes.core.helm:
        name: argocd
        chart_ref: argo/argo-cd
        namespace: argocd
        create_namespace: true
        values_files:
          - /tmp/argocd-values.yaml
        state: present

    - name: Install Repo Secret
      kubernetes.core.k8s:
        state: present
        src: /tmp/repo-secret.yaml

    - name: Install ApplicationSet
      kubernetes.core.k8s:
        state: present
        src: /tmp/applicationset.yaml