---
- name: Install packages with Arkade
  hosts: all
  become: true
  vars:
    packages:
      - yq          # Lightweight and flexible CLI YAML processor
      - fzf         # Fuzzy finder
      - helm        # Helm install tool
      - jq          # Lightweight and flexible CLI JSON processor
      - k9s         # Provides a terminal UI to interact with Kubernetes Cluster
      - krew        # Package manager for kubectl plugins
      - kubecolor   # kubectl replacement used to add colors to output
      - kubectl     # kubectl - duh
      - kubectx     # Faster way to switch contexts
      - kubens      # Switch between namespaces
      - nerdctl     # CLI for containerd
      - dive       # A tool for exploring each layer in a docker image
      
  tasks:
    - name: Install other packages
      ansible.builtin.command: arkade get {{ item }}
      retries: 5
      # creates: "/root/.arkade/bin/{{ item }}"
      with_items: "{{ packages }}"

    - name: Move packages to /usr/local/bin
      ansible.builtin.file:
        src: "/root/.arkade/bin/{{ item }}"
        dest: "/usr/local/bin/{{ item }}"
        owner: root
        group: root
        state: link
      with_items: "{{ packages }}"

      
      
