---
- name: Perform cleanup tasks
  hosts: all
  become: true

  tasks:
    - name: Check if vagrant password is still default
      ansible.builtin.expect:
        command: "su - vagrant -c 'id'"
        responses:
          (?i)Password: "vagrant"
      register: su_result
      ignore_errors: true

    - name: Change vagrant user password
      user:
        name: vagrant
        password: "{{ new_ssh_password | password_hash('sha512') }}"

      when: su_result.rc == 0 and new_ssh_password != ''

    - name: Autoremove packages
      ansible.builtin.apt:
        update_cache: true
        autoremove: true
        autoclean: true