---
- name: Perform cleanup tasks
  hosts: all
  become: true

  tasks:
    - name: Check if vagrant password is still default
      ansible.builtin.expect:
        command: "su - vagrant -c 'id'"
        responses:
          (?i)Password: "vagrant"
      register: su_result
      ignore_errors: true
      become_user: vagrant
      changed_when: "'uid=1200(vagrant) gid=1200(vagrant) groups=1200(vagrant)' in su_result.stdout"
      failed_when: false

    - name: Generate SHA512 password hash on target host
      ansible.builtin.shell: |
        python3 -c "from passlib.hash import sha512_crypt; print(sha512_crypt.hash('{{ new_ssh_password }}'))"
      args:
        executable: /bin/bash
      delegate_to: localhost
      become: false
      run_once: true
      register: password_hash_result
      when: new_ssh_password is defined and new_ssh_password != '' and su_result.rc == 0

    - name: Change vagrant user password
      ansible.builtin.user:
        name: vagrant
        password: "{{ password_hash_result.stdout }}"
      when: su_result.rc == 0 and new_ssh_password != ''

    - name: Autoremove packages
      ansible.builtin.apt:
        update_cache: true
        autoremove: true
        autoclean: true