---
- name: Perform cleanup tasks
  hosts: all
  become: true

  tasks:
    - name: Check if vagrant password is still default
      ansible.builtin.expect:
        command: "su - vagrant -c 'id'"
        responses:
          (?i)Password: "vagrant"
      register: su_result
      ignore_errors: true

    - name: Expire vagrant password if default hash
      ansible.builtin.command: passwd -e vagrant
      when: su_result.rc == 0

    - name: Autoremove packages
      ansible.builtin.apt:
        update_cache: true
        autoremove: true
        autoclean: true