---
- name: Install NeoVim
  hosts: all
  become: true

  tasks:
    - name: Install Neovim
      ansible.builtin.apt:
        update_cache: true
        name:
          - neovim

    - name: Update alternatives for editor
      community.general.alternatives:
        name: editor
        state: selected
        path: /usr/bin/nvim