---
- name: Stage 1
  hosts: all
  become: true

- name: Install prerequisite packages from Apt
  ansible.builtin.import_playbook: packages.yml

- name: Prepare system for Kubernetes
  ansible.builtin.import_playbook: prepare.yml

- name: Install containerd
  ansible.builtin.import_playbook: containerd.yml

- name: Install apps
  ansible.builtin.import_playbook: apps.yml

- name: Join to domain
  ansible.builtin.import_playbook: ad.yml

- name: Install k8s components
  ansible.builtin.import_playbook: k8s.yml

- name: Perform cleanup tasks
  ansible.builtin.import_playbook: cleanup.yml
