---
- name: Stage 1
  hosts: all
  become: true

- name: Update all packages
  ansible.builtin.import_playbook: update.yml

- name: Prepare system for Kubernetes
  ansible.builtin.import_playbook: prepare.yml

- name: Install containerd
  ansible.builtin.import_playbook: containerd.yml

- name: Install apps
  ansible.builtin.import_playbook: apps.yml

- name: Join to domain
  ansible.builtin.import_playbook: ad.yml
  vars:
    domain_password: "{{ domain_password }}"
    domain: "{{ domain }}"

- name: Perform cleanup tasks
  ansible.builtin.import_playbook: cleanup.yml
  vars:
    new_ssh_password: "{{ new_ssh_password | default('') }}"

task:
  - name: Add Kubernetes APT repository
    ansible.builtin.deb822_repository:
      name: kubernetes
      types: [deb]
      uris: "https://pkgs.k8s.io/core:/stable:/v{{ k8s_version }}/deb/"
      signed_by: "https://pkgs.k8s.io/core:/stable:/v{{ k8s_version }}/deb/Release.key"
      suites: [/]
      state: present
      enabled: yes

  - name: Install k8s tools
    ansible.builtin.apt:
      update_cache: true
      name: "{{ item }}"
      state: present
    with_items:
      - kubeadm
      - kubectl
      - kubelet