---
- name: Stage 1
  hosts: all
  become: true

- name: Install prerequisite packages from Apt
  ansible.builtin.import_playbook: packages.yaml

- name: Prepare system for Kubernetes
  ansible.builtin.import_playbook: prepare.yaml

- name: Install containerd
  ansible.builtin.import_playbook: containerd.yaml

- name: Install apps
  ansible.builtin.import_playbook: apps.yaml

- name: Join to domain
  ansible.builtin.import_playbook: ad.yaml

- name: Install k8s components
  ansible.builtin.import_playbook: k8s.yaml

- name: Perform cleanup tasks
  ansible.builtin.import_playbook: cleanup.yaml
